### ISSUE TITLE
Why a script block?

### ISSUE THREAD

**Issue by yecril71pl** [mnaoumov/Invoke-NativeApplication#3]
The command should execute a native application, not an arbitrary script block.  If you allow a script block, you encourage users to execute entire subroutines under your driver, which is not what it is for.  Also, when a failing call is a part of a larger script, it is very hard to know what actually failed.  For example, when the scripter calls a native application that is blocked by the firewall from accessing the internet, you have no idea of what failed and why.

**Comment by mnaoumov** [comment]
Fixed in #4

**Comment by yecril71pl** [comment]
Well, it is only fixed if the script developer knows how to make a script block with parameters.  I had to do it and I came up with this one:
```powershell
            [HashTable] $NativeParams = @{
                fullPSPath = $fullPSPath
                fullDotnetInstallPath = $fullDotnetInstallPath
                Channel = $Channel
                Version = $Version
            }
            If ($InstallDir) { $Params['InstallDir'] = $InstallDir }
            Start-NativeExecution {
              Param (
                  [System.IO.FileInfo] $fullPSPath,
                  [System.IO.FileInfo] $fullDotnetInstallPath,
                  [String] $Channel,
                  [String] $Version,
                  [System.IO.FileInfo] $InstallDir
              )
              If ($InstallDir) {
                  [HashTable] $InstallDirParam = @{ InstallDir = $InstallDir }
              } Else { [HashTable] $InstallDirParam = $Null }
              & $fullPSPath -NoLogo -NoProfile -File $fullDotnetInstallPath -Channel $Channel -Version $Version @InstallDirParam
            } $NativeParams
```
Note that my script contains 2 mistakes, including: `InstallDir` is not a parameter that can be reported.
Were I allowed to pass a parameter array, I could write instead:
```powershell
Start-NativeExecution $fullPSPath '-NoLogo', '-NoProfile', '-File', $fullDotnetInstallPath, '-Channel', $Channel, '-Version', $Version
```

And everything would just work.  I do not want to sound self-elevating but I am afraid the script block variant would be prohibitively hard to write for your average script kiddie next door.

**Comment by mnaoumov** [comment]
Probably we need to support both, hashtable and array

**Comment by yecril71pl** [comment]
This is not `@{}` vs `@()`, this is `{}` vs `@()`.  I would like to add another parameter set, with `[String[]] $CommandLine` instead of `[ScriptBlock] $ScriptBlock`.
